name: dream_visualizer
description: Dreamsy - AI-powered dream interpretation app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  speech_to_text: ^7.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  fl_chart: ^0.69.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  # Security & Authentication
  local_auth: ^2.1.0
  local_auth_android: ^1.0.0
  local_auth_platform_interface: ^1.0.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  # Firebase for Cloud Sync & Community
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  # Community & Social
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/audio/mic_start.mp3
    - assets/audio/mic_stop.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#1a1a1a"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
